[package]
name = "openvr"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"
build = "build/build.rs"

[dependencies]
openvr-sys = { git = "https://github.com/mickvangelderen/openvr-sys-rust", branch = "0.1.x" }
